[2024-07-24 18:44:39,604] INFO - prefect.clean_log_file | 
 <> Limpeza do arquivo de log local logs.txt realizada com sucesso.
[2024-07-24 18:44:39,607] INFO - prefect.TaskRunner | Task 'clean_log_file': Finished task run for task with final state: 'Success'
[2024-07-24 18:44:39,613] INFO - prefect.TaskRunner | Task 'run_dbt': Starting task run...
[2024-07-24 18:44:42,103] INFO - prefect.run_dbt | 
 <> Falha na transformação (DBT):  CompletedProcess(args=['dbt', 'run', '--vars', 'database: prefect_server'], returncode=2, stdout='\x1b[0m21:44:40  Running with dbt=1.8.4\n\x1b[0m21:44:40  Encountered an error:\nRuntime Error\n  No dbt_project.yml found at expected path /home/cliente/Code/RIO/desafio_data_eng/dbt_project.yml\n  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml\n  \n', stderr='') 
[2024-07-24 18:44:42,103] INFO - prefect.TaskRunner | FAIL signal raised: FAIL(None)
[2024-07-24 18:44:42,107] INFO - prefect.TaskRunner | Task 'run_dbt': Finished task run for task with final state: 'Failed'
[2024-07-24 18:44:42,114] INFO - prefect.TaskRunner | Task 'upload_logs_to_database': Starting task run...
[2024-07-24 18:44:42,119] INFO - prefect.upload_logs_to_database | 
 <> Conectado com PostgreSQL com sucesso!
[2024-07-24 18:44:42,134] INFO - prefect.upload_logs_to_database | 
 <> Tabela de logs logs__materialize criada no PostgreSQL com sucesso!
[2024-07-24 18:44:42,139] INFO - prefect.upload_logs_to_database | 
 <> Dados de logs do Flow inseridos em logs__materialize com sucesso!
[2024-07-24 18:44:42,140] INFO - prefect.upload_logs_to_database | 
 <> Feito upload do arquivo de log local logs.txt na tabela logs__materialize PostgreSQL com sucesso!
[2024-07-24 18:44:42,145] INFO - prefect.TaskRunner | Task 'upload_logs_to_database': Finished task run for task with final state: 'Success'
[2024-07-24 18:44:42,146] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
